apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: websites.kubeo.noverit.com
spec:
  # either Namespaced or Cluster
  scope: Namespaced
  # group name to use for REST API: /apis/<group>/<version>
  group: kubeo.noverit.com
  # multiple versions of the same API can be served at same type
  versions:
    - name: v1
      served: true
      storage: true
    - name: v1beta1
      served: true
      storage: false      
    - name: v1alfa2
      served: false
      storage: false
  names:
    kind: Website
    singular: website
    plural: websites
    shortNames:
    - ws
  subresources:
    status:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            gitRepo:
              type: string
            serviceType:
              type: string
            configType:
              type: string
            replicas:
              type: integer
              minimum: 0
              maximum: 9
  additionalPrinterColumns:
    - name: podReplicas
      type: integer
      description: The number of pods running
      JSONPath: .spec.replicas
    - name: ServiceType
      type: string
      description: How the website is exposed to the external
      JSONPath: .spec.serviceType
    - name: gitRepo
      type: string
      description: The Git repo where config files are stored
      JSONPath: .spec.gitRepo
    - name: ConfigType
      type: string
      description: How configurations are passed to pods
      JSONPath: .spec.configType      
    - name: Age
      type: date
      description: Creation timestamp
      JSONPath: .metadata.creationTimestamp
